### ISSUE TITLE
Sketch too big

### ISSUE THREAD

**Issue by anthonyjclarke** [VolosR/nyanCatTTGO#1]
I have an issue in Arduino when compiling, on Mac OSX, Arduino IDE 1.8.19

Sketch too big; see https://support.arduino.cc/hc/en-us/articles/360013825179 for tips on reducing it.
text section exceeds available space in board

The cat.h file seems to be the issue, how did you compile this?

**Comment by VolosR** [comment]
Hello Anthony. In Arduino IDE when selecting board , there are
default values which are too small for big sketch.  You need to set Flash
size to 8mb and Partition scheme to 8M ,
  You can see
correct settings in picture bellow.
[image: Arduino.png]



sri, 14. ruj 2022. u 04:54 Anthony Clarke ***@***.***>
napisao je:

**Comment by anthonyjclarke** [comment]
Can you please re-attach picture, did not come through

**Comment by VolosR** [comment]
Sure, i will put it in attachment

sri, 14. ruj 2022. u 06:38 Anthony Clarke ***@***.***>
napisao je:

**Comment by manj9501** [comment]
Hi @anthonyjclarke, please select Flash Size as 16MB (128Mb) and Partition Scheme as either of the two 16M Flash options as shown below:

1. Flash Size
![image](https://user-images.githubusercontent.com/36984979/190260945-2a70c637-51d3-4424-821b-2dcc5bb15d43.png)

2. Partition Scheme
![image](https://user-images.githubusercontent.com/36984979/190261157-3546c296-f826-4463-aa8c-515944d53cbe.png)

**Comment by anthonyjclarke** [comment]
Thanks, all working now.....
